# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_scheduling_v1alpha2_pod_group_scheduling_policy import IoK8sApiSchedulingV1alpha2PodGroupSchedulingPolicy

class TestIoK8sApiSchedulingV1alpha2PodGroupSchedulingPolicy(unittest.TestCase):
    """IoK8sApiSchedulingV1alpha2PodGroupSchedulingPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiSchedulingV1alpha2PodGroupSchedulingPolicy:
        """Test IoK8sApiSchedulingV1alpha2PodGroupSchedulingPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiSchedulingV1alpha2PodGroupSchedulingPolicy`
        """
        model = IoK8sApiSchedulingV1alpha2PodGroupSchedulingPolicy()
        if include_optional:
            return IoK8sApiSchedulingV1alpha2PodGroupSchedulingPolicy(
                basic = jobset.models.io/k8s/api/scheduling/v1alpha2/basic_scheduling_policy.io.k8s.api.scheduling.v1alpha2.BasicSchedulingPolicy(),
                gang = jobset.models.io/k8s/api/scheduling/v1alpha2/gang_scheduling_policy.io.k8s.api.scheduling.v1alpha2.GangSchedulingPolicy(
                    min_count = 56, )
            )
        else:
            return IoK8sApiSchedulingV1alpha2PodGroupSchedulingPolicy(
        )
        """

    def testIoK8sApiSchedulingV1alpha2PodGroupSchedulingPolicy(self):
        """Test IoK8sApiSchedulingV1alpha2PodGroupSchedulingPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
