# coding: utf-8

"""
    JobSet SDK

    Python SDK for the JobSet API

    The version of the OpenAPI document: v0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jobset.models.io_k8s_api_scheduling_v1alpha2_topology_constraint import IoK8sApiSchedulingV1alpha2TopologyConstraint

class TestIoK8sApiSchedulingV1alpha2TopologyConstraint(unittest.TestCase):
    """IoK8sApiSchedulingV1alpha2TopologyConstraint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IoK8sApiSchedulingV1alpha2TopologyConstraint:
        """Test IoK8sApiSchedulingV1alpha2TopologyConstraint
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IoK8sApiSchedulingV1alpha2TopologyConstraint`
        """
        model = IoK8sApiSchedulingV1alpha2TopologyConstraint()
        if include_optional:
            return IoK8sApiSchedulingV1alpha2TopologyConstraint(
                key = ''
            )
        else:
            return IoK8sApiSchedulingV1alpha2TopologyConstraint(
                key = '',
        )
        """

    def testIoK8sApiSchedulingV1alpha2TopologyConstraint(self):
        """Test IoK8sApiSchedulingV1alpha2TopologyConstraint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
