# golangci-lint configuration file
# see: https://golangci-lint.run/usage/configuration/

# Options for analysis running
run:
  # Which dirs to skip: they won't be analyzed;
  skip-dirs:
    - bin

# Settings of specific linters
linters-settings:
  goimports:
    local-prefixes: sigs.k8s.io/jobset

# Settings for enabling and disabling linters
linters:
  enable:
    - goimports
    - unparam
