apiVersion: jobset.x-k8s.io/v1beta1
kind: JobSet
metadata:
  name: jobset-no-ttl
spec:
  replicatedJobs:
  - name: workers
    template:
      spec:
        parallelism: 4
        completions: 4
        backoffLimit: 0
        template:
          spec:
            containers:
            - name: sleep
              image: busybox
              command:
                - sleep
              args:
                - 10s
